//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginAndRegister_.NetFrameworkMVC_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        public int IdProyecto { get; set; }
        public string NombreProyecto { get; set; }
        public string TipoProyecto { get; set; }
        public string NombreDesarrollador { get; set; }
        public System.DateTime FechaAsignacion { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public double PrecioProyecto { get; set; }
    }
}
